# Generated by Django 5.1.6 on 2025-02-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('poste', models.CharField(max_length=100)),
                ('niveau_seniorite', models.CharField(max_length=50)),
                ('date_embauche', models.DateField()),
                ('salaire_brut_annuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_annuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('Actif', 'Actif'), ('En congé', 'En congé'), ('Partant', 'Partant')], max_length=50)),
            ],
        ),
    ]
